#!/usr/bin/env node
/**
 * Rebuild src/assets/vendor/a2ui-v0_9.js: the A2UI web renderer (protocol
 * v0.9) as ONE ES module, so the dashboard can load it with
 * <script type="module"> under its CSP (no CDN scripts allowed). Run it when
 * bumping the pinned versions below; the output is checked in.
 *
 *   node packages/dashboard/scripts/vendor-a2ui.mjs
 *
 * Versions must match @a2ui/web_core in packages/core/package.json (the
 * server validates views with the same code). See docs/adr/0047-a2ui-views.md.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const VERSIONS = { lit: '0.12.0', webCore: '0.12.0', esbuild: '0.25.12' };
const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '..', 'src', 'assets', 'vendor', 'a2ui-v0_9.js');
const dir = mkdtempSync(join(tmpdir(), 'sua-a2ui-vendor-'));
try {
  writeFileSync(join(dir, 'package.json'), JSON.stringify({ name: 'a2ui-vendor', private: true, type: 'module' }));
  execFileSync('npm', ['install', '--silent', '--no-audit', '--no-fund',
    `@a2ui/lit@${VERSIONS.lit}`, `@a2ui/web_core@${VERSIONS.webCore}`, `esbuild@${VERSIONS.esbuild}`], { cwd: dir, stdio: 'inherit' });
  writeFileSync(join(dir, 'entry.js'), [
    '// sua\'s vendored A2UI renderer (v0.9 protocol). Generated by scripts/vendor-a2ui.mjs; do not edit.',
    "export { MessageProcessor, Catalog, CommonSchemas } from '@a2ui/web_core/v0_9';",
    "export { setMarkdownRenderer } from '@a2ui/web_core/v0_9/basic_catalog';",
    "export { A2uiSurface, A2uiLitElement, basicCatalog } from '@a2ui/lit/v0_9';",
    "export { html, css, nothing } from 'lit';",
    "export { z } from 'zod';",
    '',
  ].join('\n'));
  execFileSync(join(dir, 'node_modules', '.bin', 'esbuild'), [
    'entry.js', '--bundle', '--format=esm', '--minify', '--target=es2022', '--legal-comments=eof', `--outfile=${out}`,
  ], { cwd: dir, stdio: 'inherit' });
  console.log(`wrote ${out} (${Math.round(statSync(out).size / 1024)} KB)`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}
