/**
 * Output widget schema. Agents declare an `outputWidget` that tells the
 * dashboard how to render their run output as a structured widget instead
 * of raw text. This decouples agent output presentation from dashboard code.
 */

/** Field type determines rendering: text is plain, code gets monospace+scroll,
 *  badge gets a colored pill, action renders a button, metric renders a big number,
 *  stat renders a compact label+value pair in a grid, preview renders a file
 *  in a sandboxed iframe via the /output-file route. */
export type WidgetFieldType = 'text' | 'code' | 'badge' | 'action' | 'metric' | 'stat' | 'preview';

export interface WidgetField {
  /** Key in the structured output to extract this field from. */
  name: string;
  /** Display label. Defaults to `name` if omitted. */
  label?: string;
  /** How to render the field value. */
  type: WidgetFieldType;
}

export interface WidgetAction {
  /** Unique action identifier. */
  id: string;
  /** Button label. */
  label: string;
  /** HTTP method (only POST supported initially). */
  method: 'POST';
  /** Endpoint path. `{agentId}` is replaced with the agent's id at render time. */
  endpoint: string;
  /** Which field's value to send as the request body payload. */
  payloadField?: string;
}

export type OutputWidgetType = 'diff-apply' | 'key-value' | 'raw' | 'dashboard' | 'ai-template';

export interface OutputWidgetSchema {
  /** Widget type determines the layout and rendering strategy. */
  type: OutputWidgetType;
  /** Fields to extract from the run output and display. Required for non ai-template widgets. */
  fields?: WidgetField[];
  /** Interactive actions (buttons) the user can trigger from the widget. */
  actions?: WidgetAction[];
  /** ai-template: original prompt the user wrote (kept for iteration). */
  prompt?: string;
  /**
   * ai-template: sanitized HTML template with `{{outputs.NAME}}` placeholders
   * (and `{{result}}` for the raw run output). Generated by an LLM and stored
   * verbatim. Re-rendered at run time by substituting + sanitizing.
   */
  template?: string;
  /**
   * Interactive widget mode. When true, the dashboard renders the widget with
   * an inline inputs form + Run button so users can trigger fresh runs from
   * the tile without navigating away. Result polls in via the widget-status
   * endpoint. Default false; existing widgets render in static mode.
   */
  interactive?: boolean;
  /**
   * Subset of `agent.inputs` names to expose in the interactive tile. If
   * absent (and `interactive` is true), every declared input is shown.
   */
  runInputs?: string[];
  /** Override label for the initial run button. Default "Run". */
  askLabel?: string;
  /** Override label for the post-result replay button. Default "Run again". */
  replayLabel?: string;
}
