/**
 * Output widget schema. Agents declare an `outputWidget` that tells the
 * dashboard how to render their run output as a structured widget instead
 * of raw text. This decouples agent output presentation from dashboard code.
 */

/** Field type determines rendering: text is plain, code gets monospace+scroll,
 *  badge gets a colored pill, action renders a button, metric renders a big number,
 *  stat renders a compact label+value pair in a grid, preview renders a file
 *  in a sandboxed iframe via the /output-file route, table renders a row-per-
 *  item table over a top-level array. */
export type WidgetFieldType = 'text' | 'code' | 'badge' | 'action' | 'metric' | 'stat' | 'preview' | 'table';

/** Cell render mode within a `table` field column. `text` (default) escapes the
 *  value as plain text; `link` wraps the cell in an `<a>` using `href` (a row-
 *  key name resolved per-row) and `text` (a row-key name OR a literal string)
 *  to drive what's shown. */
export type TableColumnFormat = 'text' | 'link';

/** One column in a `table` field. `name` is the per-row JSON key whose value
 *  drives the cell. `format` picks the cell render; for `link`, `href` names a
 *  per-row key holding the URL, and optional `text` either names a per-row key
 *  for the displayed text or — when no such key exists on the row — falls back
 *  to a literal string (e.g. `"Open"`). */
export interface TableColumn {
  name: string;
  label?: string;
  format?: TableColumnFormat;
  href?: string;
  text?: string;
}

export interface WidgetField {
  /** Key in the structured output to extract this field from. For `table`
   *  fields, this is the name of the top-level array (e.g. `matches`). */
  name: string;
  /** Display label. Defaults to `name` if omitted. */
  label?: string;
  /** How to render the field value. */
  type: WidgetFieldType;
  /** Required when `type` is `table`. One entry per column, in display order. */
  columns?: TableColumn[];
}

export interface WidgetAction {
  /** Unique action identifier. */
  id: string;
  /** Button label. */
  label: string;
  /** HTTP method (only POST supported initially). */
  method: 'POST';
  /** Endpoint path. `{agentId}` is replaced with the agent's id at render time. */
  endpoint: string;
  /** Which field's value to send as the request body payload. */
  payloadField?: string;
}

export type OutputWidgetType = 'diff-apply' | 'key-value' | 'raw' | 'dashboard' | 'ai-template';

export interface OutputWidgetSchema {
  /** Widget type determines the layout and rendering strategy. */
  type: OutputWidgetType;
  /** Fields to extract from the run output and display. Required for non ai-template widgets. */
  fields?: WidgetField[];
  /** Interactive actions (buttons) the user can trigger from the widget. */
  actions?: WidgetAction[];
  /** ai-template: original prompt the user wrote (kept for iteration). */
  prompt?: string;
  /**
   * ai-template: sanitized HTML template with `{{outputs.NAME}}` placeholders
   * (and `{{result}}` for the raw run output). Generated by an LLM and stored
   * verbatim. Re-rendered at run time by substituting + sanitizing.
   */
  template?: string;
  /**
   * Interactive widget mode. When true, the dashboard renders the widget with
   * an inline inputs form + Run button so users can trigger fresh runs from
   * the tile without navigating away. Result polls in via the widget-status
   * endpoint. Default false; existing widgets render in static mode.
   */
  interactive?: boolean;
  /**
   * Subset of `agent.inputs` names to expose in the interactive tile. If
   * absent (and `interactive` is true), every declared input is shown.
   */
  runInputs?: string[];
  /** Override label for the initial run button. Default "Run". */
  askLabel?: string;
  /** Override label for the post-result replay button. Default "Run again". */
  replayLabel?: string;
  /**
   * Inline interactive controls rendered above the widget body. Allow the
   * viewer to re-run the agent, hide/show optional fields, or switch between
   * named views. State is URL-driven (no client JS).
   */
  controls?: WidgetControl[];
  /**
   * How the widget tile's HEIGHT behaves on a Pulse/dashboard when its content
   * is taller than the slot. Width is always the dashboard-defined grid column.
   * Only affects tiles — the full run/agent view always renders at natural
   * height.
   *   - `grow` (default): the tile grows vertically to the widget's height — no
   *     scroll, fully readable; the grid row sizes to it.
   *   - `scroll`: cap the tile height and scroll the overflow.
   */
  tileFit?: 'grow' | 'scroll';
}

/** A named subset of widget fields used by `view-switch` controls. */
export interface WidgetView {
  id: string;
  fields: string[];
}

export type WidgetControl =
  | {
      type: 'replay';
      label?: string;
      /** Subset of agent.inputs to expose for tweaking on replay. */
      inputs?: string[];
    }
  | {
      type: 'field-toggle';
      label: string;
      fields: string[];
      default: 'shown' | 'hidden';
    }
  | {
      type: 'view-switch';
      label: string;
      views: WidgetView[];
      default: string;
    }
  | {
      /**
       * Sort the named top-level array in `outputs` by a column the viewer
       * picks. State via `?ws=<column>-<asc|desc>`. Stable; ties keep input
       * order. Numeric / string / boolean / null are all supported — type is
       * inferred per column at sort time from the actual data.
       */
      type: 'sort';
      label?: string;
      /** Top-level array name in the parsed JSON (no `outputs.` prefix). */
      field: string;
      columns: string[];
      /** Initial sort, e.g. `"cost"` or `"cost desc"`. */
      default?: string;
    }
  | {
      /**
       * Filter the named array by case-insensitive substring across the
       * specified columns. State via `?wf=<query>`. Survives if ANY listed
       * column's stringified value contains the query.
       */
      type: 'filter';
      label?: string;
      field: string;
      columns: string[];
      placeholder?: string;
    }
  | {
      /**
       * Slice the named array into pages of `pageSize` rows. State via
       * `?wp=<n>` (1-based). Applied AFTER filter and sort so pagination
       * reflects the visible (filtered+sorted) set.
       */
      type: 'paginate';
      field: string;
      pageSize: number;
    };
